version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: wb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgres://user:password@db:5432/wildberries
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data:
